### PR TITLE
Fix file attachments and equations and enhance emails from org-files

### PR DESCRIPTION
**Pull request by jkitchin**
Major changes:
1. I think that file links should be attachments in an email. This commit makes
that happen. It should work in all three ways of making/sending messages.
2. Add file keyword support for email headers when using
org-mime-org-buffer-htmlize, and update docstrings.
3. Equations were not getting correctly handled in org-mime-org-buffer-htmlize
and org-mime-org-subtree-htmlize. The images were not getting created and
attached correctly. This commit fixes that.
4. org-mim--chomp is too aggressive, and does more than the docstring suggests.
I changed the docstring, and removed the call to it in org-mime-htmlize. Now the
function is not used anywhere, so it could be removed. It would be preferrable
to use something like s-trim.
5. It should be possible to use relative paths to images.
6. Add an ascii export to org-mime-htmlize. Previously no export was done for
the plain mimepart. Some links don't make sense in the email then, so adding the
ascii export allows them to be re-rendered in a way that does make sense. The
most concrete example is a cite/bibliography link from org-ref, which now get
converted to ascii representations when the email is htmlized.

Minor fixes:
1. org-export-htmlize-output-type is no longer a variable in org-9. It is now
org-html-htmlize-output-type. Both variables are still used for backward
compatibility.
2. a few typos
3. Some comment clarifications

### CODE REVIEW

**Comment by jkitchin** [comment]
I have tested this on all three modes (message, subtree and buffer) with images, equations, files and org-links. As far as I can see, they all work. The only nuisance thing that still bothers me is some html links show up that don't point to anything. That has always been the case though, e.g. links in the toc. It is only annoying if you click on them and they go to page that does not exist.

**Comment by redguardtoo** [comment]
Cool, so you also tested on Emacs 24.4?

**Comment by jkitchin** [comment]
I don't have an emacs 24.4 to test on.

**Comment by redguardtoo** [comment]
OK, I will test on Emacs 24.4. Give me some time.

What emacs version you tested on? If you have time, could you install Emacs 24 to test (it's totally portable, see https://gist.github.com/redguardtoo/4c163d2da1736a988b922ce3b2fe4ba4) ?

**Comment by redguardtoo** [comment]
`org-element-map` is not defined in Emacs 24 and 25.

Could you test in Emacs 24 and Emacs 25?

**Comment by jkitchin** [comment]
Why would you want to resend a mail? I think it would also be fine to export org to org. the point is some links need to be modified by export for them to make sense in an email. For example, a bibliography link needs to be expanded to a full bibliography.

org-element-map might be an org 9.0 feature. I don't know an easy way to solve these problems on org 8.0. I guess that could be wrapped with a check and a message that it doesn't work on org 8?

**Comment by redguardtoo** [comment]
OK, I might figure out a workaround this weekend, could you show me some sample org file and screenshots of expected output?

**Comment by jkitchin** [comment]
For example, in org I might write:

```
This is an interesting article cite:kitchin-2015-examp.


bibliography:~/bibliography/references.bib
```

That is not helpful to anyone getting the email. If I export it to org, it becomes:

```
This is an interesting article [[#kitchin-2015-examp][kitchin-2015-examp]].


* Bibliography
** Kitchin, John R. - Examples of Effective Data Sharing in Scientific Publishing
  :PROPERTIES:
   :CUSTOM_ID: kitchin-2015-examp
   :=TYPE=: article
   :=KEY=: kitchin-2015-examp
   :AUTHOR: {Kitchin, John R.}
   :TITLE: {Examples of Effective Data Sharing in Scientific Publishing}
   :JOURNAL: {ACS Catalysis}
   :VOLUME: {5}
   :NUMBER: {6}
   :PAGES: {3894-3899}
   :YEAR: 2015
   :DOI: {10.1021/acscatal.5b00538}
   :URL: { http://dx.doi.org/10.1021/acscatal.5b00538 }
   :KEYWORDS: {DESC0004031, early-career, orgmode, Data sharing }
   :EPRINT: { http://dx.doi.org/10.1021/acscatal.5b00538 }
  :END:
```
which is more helpful.

**Comment by redguardtoo** [comment]
Do you use `org-mime-fixedwith-wrap`? I need clean code a little bit before accepting your pull request.

**Comment by jkitchin** [comment]
I have not used that function.

**Comment by redguardtoo** [comment]
Hi, @jkitchin,

I clean your code a little bit. See https://github.com/org-mime/org-mime/tree/work

Please test the code, is still working in your Emacs.

You could close this pull request  and create new pull request based on `work` branch if you got some new fix.

**Pull request closed without merging**
