### PR TITLE
plain text -> Gmail blockquote parser

### PR DESCRIPTION
**Pull request by tmurph**

### CODE REVIEW

**Comment by redguardtoo** [comment]
Could you test code on Emacs 24.3, 24.4, 25.3?

**Comment by tmurph** [comment]
With respect, I don't know what tests you're asking me to do.  I don't see any tests in this repo, so whatever testing you're doing I can't repeat.  

The patch doesn't use any features that depend on higher versions of Emacs, so it should work on 24.3 and higher.

How do you test your library on your setup?

**Comment by tmurph** [comment]
Re: squash, I can't really rewrite git history at this point.  However, github has an option to squash all commits on merge, so you can do the squash automatically when you merge the pull request.

https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by redguardtoo** [comment]
thanks. I tested with `24.4`. Looks good.

**Pull request merged**
